font:
  normal:
    family: Cascadia Code
    style: Regular

  bold:
    family: Cascadia Code
    style: Bold

  italic:
    family: Cascadia Code
    style: Italic

  bold_italic:
    family: Cascadia Code
    style: Bold Italic

  size: 10

window:
  padding:
    x: 15
    y: 15

colors:
  primary:
    background: '#232136'
